### ISSUE TITLE
looking forward to meeting the coding

### ISSUE THREAD

**Issue by liuchanfeng165** [gidariss/wDAE_GNN_FewShot#3]
（Smile）

**Comment by gidariss** [comment]
Hi, I uploaded the code for the Image-Net based experiments. Soon, I will also upload the code for the MiniImageNet based experiments.

**Comment by liuchanfeng165** [comment]
> Hi, I uploaded the code for the Image-Net based experiments. Soon, I will also upload the code for the MiniImageNet based experiments.

Thanks a lot！
